/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtnCalculate: typeof import('./components/home/BtnCalculate.vue')['default']
    BtnScroll: typeof import('./components/home/BtnScroll.vue')['default']
    CardHome: typeof import('./components/home/CardHome.vue')['default']
    CardResult: typeof import('./components/result/CardResult.vue')['default']
    CarouselCategory: typeof import('./components/home/CarouselCategory.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PaginationResult: typeof import('./components/result/PaginationResult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectStock: typeof import('./components/home/SelectStock.vue')['default']
    TableCategory: typeof import('./components/home/TableCategory.vue')['default']
    TableResult: typeof import('./components/result/TableResult.vue')['default']
  }
}
